services:
  - type: web
    name: Tesis_Crsitian_Domecq
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Tesis_Crsitian_Domecq.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Tesis_Crsitian_Domecq.settings
