# Generated by Django 5.2.4 on 2025-07-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciudad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(choices=[('Asunción', 'Asunción'), ('San Lorenzo', 'San Lorenzo'), ('Capiatá', 'Capiatá'), ('Lambaré', 'Lambaré'), ('Fernando de la Mora', 'Fernando de la Mora'), ('Luque', 'Luque'), ('Mariano Roque Alonso', 'Mariano Roque Alonso'), ('Limpio', 'Limpio'), ('Ñemby', 'Ñemby'), ('Itauguá', 'Itauguá'), ('Villa Elisa', 'Villa Elisa'), ('San Antonio', 'San Antonio'), ('Villa Hayes', 'Villa Hayes'), ('San Juan Bautista', 'San Juan Bautista'), ('Encarnación', 'Encarnación'), ('Ciudad del Este', 'Ciudad del Este'), ('Hernandarias', 'Hernandarias'), ('Presidente Franco', 'Presidente Franco'), ('CDE (Mcal. Estigarribia)', 'CDE (Mcal. Estigarribia)'), ('Caaguazú', 'Caaguazú'), ('Coronel Oviedo', 'Coronel Oviedo'), ('Villarrica', 'Villarrica'), ('Pilar', 'Pilar'), ('Caazapá', 'Caazapá'), ('Caacupé', 'Caacupé'), ('San Juan Nepomuceno', 'San Juan Nepomuceno'), ('Paraguarí', 'Paraguarí'), ('Areguá', 'Areguá'), ('Ypacaraí', 'Ypacaraí'), ('Pirayú', 'Pirayú'), ('Jesús', 'Jesús'), ('San Bernardino', 'San Bernardino'), ('Altos', 'Altos'), ('Ypané', 'Ypané'), ('Yaguaron', 'Yaguaron'), ('Tobatí', 'Tobatí'), ('Carapeguá', 'Carapeguá'), ('Nueva Colombia', 'Nueva Colombia'), ('Villa Rica', 'Villa Rica'), ('Arroyos y Esteros', 'Arroyos y Esteros'), ('San Estanislao', 'San Estanislao'), ('Horqueta', 'Horqueta'), ('Concepción', 'Concepción'), ('San Lázaro', 'San Lázaro'), ('Loma Grande', 'Loma Grande'), ('Santa Rosa del Aguaray', 'Santa Rosa del Aguaray'), ('Curuguaty', 'Curuguaty'), ('Villa del Rosario', 'Villa del Rosario'), ('Bella Vista', 'Bella Vista'), ('Pedro Juan Caballero', 'Pedro Juan Caballero'), ('Salto del Guairá', 'Salto del Guairá'), ('Doctor Juan León Mallorquín', 'Doctor Juan León Mallorquín'), ('Hohenau', 'Hohenau'), ('Buenos Aires', 'Buenos Aires'), ('Santa Rita', 'Santa Rita'), ('Nueva Esperanza', 'Nueva Esperanza'), ('Pozo Colorado', 'Pozo Colorado'), ('José Falcón', 'José Falcón'), ('La Victoria', 'La Victoria'), ('Mariscal Estigarribia', 'Mariscal Estigarribia'), ('Villa Oliva', 'Villa Oliva'), ('Humaitá', 'Humaitá'), ('Ayolas', 'Ayolas'), ('San Cosme y Damián', 'San Cosme y Damián'), ('General Delgado', 'General Delgado'), ('Itá', 'Itá'), ('Piribebuy', 'Piribebuy'), ('Guarambaré', 'Guarambaré'), ('Villeta', 'Villeta'), ('Nueva Italia', 'Nueva Italia'), ('Ypane', 'Ypane')], unique=True)),
                ('departamento', models.CharField(choices=[('Alto Paraguay', 'Alto Paraguay'), ('Alto Paraná', 'Alto Paraná'), ('Amambay', 'Amambay'), ('Boquerón', 'Boquerón'), ('Caaguazú', 'Caaguazú'), ('Caazapá', 'Caazapá'), ('Canindeyú', 'Canindeyú'), ('Central', 'Central'), ('Concepción', 'Concepción'), ('Guairá', 'Guairá'), ('Itapúa', 'Itapúa'), ('Cordillera', 'Cordillera'), ('Misiones', 'Misiones'), ('Ñeembucú', 'Ñeembucú'), ('Paraguarí', 'Paraguarí'), ('Presidente Hayes', 'Presidente Hayes'), ('San Pedro', 'San Pedro')])),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('Pasaporte', 'Pasaporte'), ('RUC', 'RUC'), ('CI', 'CI')], default='CI')),
                ('numero_documento', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado'), ('Cerrado', 'Cerrado'), ('Pendiente', 'Pendiente'), ('Suspendido', 'Suspendido'), ('En revisión', 'En revisión')], default='Activo')),
                ('custom_username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_personas', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_personas_permissions', to='auth.permission', verbose_name='user permissions')),
                ('ciudad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Sin calificación', 'Sin calificación')])),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado'), ('Cerrado', 'Cerrado'), ('En revisión', 'En revisión'), ('Suspendido', 'Suspendido')])),
                ('persona_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cuenta', models.PositiveIntegerField(blank=True, editable=False, unique=True)),
                ('nro_contrato', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('tipo_cuenta', models.CharField(choices=[('Cuenta Corriente', 'Cuenta Corriente'), ('Cuenta de Ahorro', 'Cuenta de Ahorro')])),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Bloqueada', 'Bloqueada'), ('Cerrada', 'Cerrada'), ('Pendiente de aprobación', 'Pendiente de aprobación'), ('Suspendida', 'Suspendida'), ('En revisión', 'En revisión'), ('En mora', 'En mora')], default='Activa')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promedio_acreditacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moneda', models.CharField(choices=[('Gs', 'Guaraní'), ('USD', 'Dolares_Americanos')])),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito')])),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_movimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_origen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_destino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal', models.CharField(choices=[('App', 'Aplicacion'), ('Web', 'Pagina')], default='Web')),
                ('cuenta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cuentas')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nro_cuenta', models.PositiveIntegerField(unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('Cuenta Corriente', 'Cuenta Corriente'), ('Cuenta de Ahorro', 'Cuenta de Ahorro')])),
                ('moneda', models.CharField(choices=[('Gs', 'Guaraní'), ('USD', 'Dolares_Americanos')])),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('Pasaporte', 'Pasaporte'), ('RUC', 'RUC'), ('CI', 'CI')])),
                ('numero_documento', models.CharField(max_length=255)),
                ('cliente_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_propietario', to='cliente.cliente')),
                ('cliente_registrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_registrado', to='cliente.cliente')),
            ],
        ),
    ]
