# Generated by Django 5.2.4 on 2025-07-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='cuenta_id',
        ),
        migrations.RemoveField(
            model_name='relacioncliente',
            name='cliente_propietario',
        ),
        migrations.RemoveField(
            model_name='relacioncliente',
            name='cliente_registrado',
        ),
        migrations.DeleteModel(
            name='Cuentas',
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
        migrations.DeleteModel(
            name='RelacionCliente',
        ),
    ]
