# Generated by Django 5.2.4 on 2025-07-22 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_remove_movimientos_cuenta_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_equipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('descripcion_falla', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('solucion', models.TextField(blank=True)),
                ('potencia_hp_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('voltaje', models.PositiveIntegerField(blank=True, null=True)),
                ('rpm', models.PositiveIntegerField(blank=True, null=True)),
                ('fase', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_trabajo', models.CharField(blank=True, max_length=15, unique=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En Diagnostico', 'En Diagnostico'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('No retirado', 'No retirado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Falta de pago', 'Falta de pago')], default='Recibido')),
                ('diagnostico_tecnico', models.TextField(blank=True, null=True)),
                ('solucion_aplicada', models.TextField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.equipo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordentrabajo')),
            ],
            options={
                'unique_together': {('orden', 'equipo')},
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='equipos',
            field=models.ManyToManyField(blank=True, related_name='ordenes', through='ordenes.OrdenTrabajoEquipo', to='ordenes.equipo'),
        ),
    ]
