# Generated by Django 5.2.4 on 2025-07-22 03:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['tipo_equipo', 'marca', 'modelo'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajoequipo',
            options={'ordering': ['fecha_asociacion'], 'verbose_name': 'Equipo en Orden de Trabajo', 'verbose_name_plural': 'Equipos en Órdenes de Trabajo'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajoequipo',
            name='costo_reparacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de reparación para este equipo específico', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajoequipo',
            name='estado_equipo_en_orden',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Diagnóstico', 'En Diagnóstico'), ('En Reparación', 'En Reparación'), ('Reparado', 'Reparado'), ('No Reparable', 'No Reparable')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fase',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Monofásico'), (2, 'Bifásico'), (3, 'Trifásico')], null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='potencia_hp_kw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potencia en HP o KW', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='rpm',
            field=models.PositiveIntegerField(blank=True, help_text='Revoluciones por minuto', null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('Motor', 'Motor Eléctrico'), ('Bomba', 'Bomba'), ('Ventilador', 'Ventilador'), ('Compresor', 'Compresor'), ('Generador', 'Generador'), ('Transformador', 'Transformador'), ('Otro', 'Otro')], default='Motor', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='voltaje',
            field=models.PositiveIntegerField(blank=True, help_text='Voltaje en V', null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='equipos',
            field=models.ManyToManyField(blank=True, related_name='ordenes_trabajo', through='ordenes.OrdenTrabajoEquipo', to='ordenes.equipo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En Diagnostico', 'En Diagnóstico'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('No retirado', 'No retirado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Falta de pago', 'Falta de pago')], default='Recibido', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajoequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_ordenes', to='ordenes.equipo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajoequipo',
            name='fecha_asociacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajoequipo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_equipos', to='ordenes.ordentrabajo'),
        ),
    ]
