# Generated by Django 5.2.4 on 2025-07-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_equipo_options_alter_ordentrabajo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='numero_serie',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('Motor', 'Motor Eléctrico'), ('Bomba', 'Bomba'), ('Ventilador', 'Ventilador'), ('Compresor', 'Compresor'), ('Generador', 'Generador'), ('Transformador', 'Transformador'), ('Otro', 'Otro')], default='Motor', max_length=100),
        ),
    ]
