# Generated by Django 5.2.4 on 2025-07-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_remove_equipo_numero_serie_alter_equipo_tipo_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='diagnostico_tecnico',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_diagnostico',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='solucion_aplicada',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_diagnostico',
            field=models.DateField(blank=True, null=True),
        ),
    ]
