# Generated by Django 5.2.4 on 2025-07-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ciudad_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='persona_id',
        ),
        migrations.RemoveField(
            model_name='cuentas',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='cuenta_id',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cuentas',
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
    ]
